[package]
name = "rustling"
version = "0.1.0"
authors = ["Jinzo <gilberto.veras@aol.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.32.1"
features = ["bundled", "static-link"]

[dependencies]
glium = "0.23.0"